### ISSUE TITLE
Add an open-source license 

### ISSUE THREAD

**Issue by teiesti** [MMXVII/mmix#1]
It might be a little to early for that, but since we want to publish our software on crates.io in the end, we have to commit to an open-source license.

And since we are all authors, we have to find one together.

(I created this issue, so we won't forget!)
(Okay, I did also test issues with this issue...)

**Comment by folkengine** [comment]
I would really love it if you resolved this issue. Thanks!

**Comment by teiesti** [comment]
We will discuss this.
