### ISSUE TITLE
Implement the special registers

### ISSUE THREAD

**Issue by teiesti** [MMXVII/mmix#9]
This includes the information which register be accessed by the programmer using PUT. See page 21 in THE BOOK.

**Comment by BarbaraButz** [comment]
@teiesti Is there any reason why the enum R in sr.rs is not public?

**Comment by teiesti** [comment]
I see no reason. Looks like a bug! Would you write a fix and open a pull-request to see what the others say?

**Comment by BarbaraButz** [comment]
Will do.
Edit: #23
